### ISSUE TITLE
Unable to locate PKG


### ISSUE THREAD

**Issue by Gul733** [rendiix/termux-zipalign#1]
![Screenshot_20220215-145058.png](https://user-images.githubusercontent.com/98087836/154037099-4dabc455-deae-4fa3-87d1-fa61abfbacf7.png)
Plz check img
Termux

**Comment by Gul733** [comment]
Problem solved

In Termux use aapt to install zipalign
For example
pkg install aapt

**Comment by rendiix** [comment]
> ![Screenshot_20220215-145058.png](https://user-images.githubusercontent.com/98087836/154037099-4dabc455-deae-4fa3-87d1-fa61abfbacf7.png) Plz check img Termux

it's just a copy paste problem

Copy this
```console
curl -s https://raw.githubusercontent.com/rendiix/rendiix.github.io/master/install-repo.sh | bash
```
```console
pkg install zipalign
```
